### ISSUE TITLE
Proof it steals your Ip

### ISSUE THREAD

**Issue by iamhereforsomereason** [j6xontop/jVoid#32]
![IMG_2971](https://user-images.githubusercontent.com/130681434/232354420-9e456af9-20ba-42b8-b936-b2f7946929af.png)

**Comment by j6xontop** [comment]
its a joke lmao

**Comment by iamhereforsomereason** [comment]
\
![image](https://user-images.githubusercontent.com/130681434/232788747-09e51d4a-c707-4027-8f56-71e932a66cfd.png)
 you expect me to believe that?

**Comment by j6xontop** [comment]
i am the owner, my devs dont log.
